# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 1048576);
user_pref("calendar.list.sortOrder", "c468be2b-56d2-4838-9426-27c1902112b4");
user_pref("calendar.registry.c468be2b-56d2-4838-9426-27c1902112b4.calendar-main-default", true);
user_pref("calendar.registry.c468be2b-56d2-4838-9426-27c1902112b4.calendar-main-in-composite", true);
user_pref("calendar.registry.c468be2b-56d2-4838-9426-27c1902112b4.name", "Casa");
user_pref("calendar.registry.c468be2b-56d2-4838-9426-27c1902112b4.type", "storage");
user_pref("calendar.registry.c468be2b-56d2-4838-9426-27c1902112b4.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Madrid");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 6);
user_pref("extensions.enabledAddons", "langpack-es-ES@thunderbird.mozilla.org:8.0,langpack-en-GB@thunderbird.mozilla.org:8.0,messagingmenu@mozilla.com:0.8.3,edsintegration@mozilla.com:0.3.8,langpack-es-AR@thunderbird.mozilla.org:8.0,{847b3a00-7ab1-11d4-8f02-006008948af5}:1.3.4,{e2fda1a4-762b-4020-b5ad-a41df1933103}:1.0,{972ce4c6-7e08-4474-a285-3208198ce6fd}:8.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"langpack-es-ES@thunderbird.mozilla.org\":{\"descriptor\":\"/usr/lib/thunderbird-8.0/extensions/langpack-es-ES@thunderbird.mozilla.org.xpi\",\"mtime\":1322168549000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/thunderbird-8.0/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1326068171000},\"langpack-en-GB@thunderbird.mozilla.org\":{\"descriptor\":\"/usr/lib/thunderbird-8.0/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"mtime\":1322168549000},\"messagingmenu@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird-8.0/extensions/messagingmenu@mozilla.com.xpi\",\"mtime\":1322168380000},\"edsintegration@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird-8.0/extensions/edsintegration@mozilla.com.xpi\",\"mtime\":1322168381000},\"langpack-es-AR@thunderbird.mozilla.org\":{\"descriptor\":\"/usr/lib/thunderbird-8.0/extensions/langpack-es-AR@thunderbird.mozilla.org.xpi\",\"mtime\":1322168549000}}},{\"name\":\"app-profile\",\"addons\":{\"{847b3a00-7ab1-11d4-8f02-006008948af5}\":{\"descriptor\":\"/home/test/.thunderbird/1wa1ghks.default/extensions/{847b3a00-7ab1-11d4-8f02-006008948af5}\",\"mtime\":1326118401000},\"{e2fda1a4-762b-4020-b5ad-a41df1933103}\":{\"descriptor\":\"/home/test/.thunderbird/1wa1ghks.default/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}\",\"mtime\":1326118401000}}}]");
user_pref("extensions.lastAppVersion", "8.0");
user_pref("extensions.lastPlatformVersion", "8.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", false);
user_pref("ldap_2.servers.eds.description", "EDS Address Book Bootstrapper");
user_pref("ldap_2.servers.eds.dirType", 3);
user_pref("ldap_2.servers.eds.filename", "eds.mab");
user_pref("ldap_2.servers.eds.position", 1);
user_pref("ldap_2.servers.eds.uri", "moz-abedsdirectory://");
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.rights.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "8.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Trabajo");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Por hacer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Más tarde");
user_pref("mailnews.tags.version", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
