# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 155790);
user_pref("calendar.list.sortOrder", "253161af-052e-4251-9c64-16ba11b686fb");
user_pref("calendar.registry.253161af-052e-4251-9c64-16ba11b686fb.calendar-main-default", true);
user_pref("calendar.registry.253161af-052e-4251-9c64-16ba11b686fb.calendar-main-in-composite", true);
user_pref("calendar.registry.253161af-052e-4251-9c64-16ba11b686fb.name", "Casa");
user_pref("calendar.registry.253161af-052e-4251-9c64-16ba11b686fb.type", "storage");
user_pref("calendar.registry.253161af-052e-4251-9c64-16ba11b686fb.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Africa/Abidjan");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 6);
user_pref("extensions.enabledAddons", "edsintegration@mozilla.com:0.3.9,langpack-es-AR@thunderbird.mozilla.org:9.0,langpack-es-ES@thunderbird.mozilla.org:9.0,messagingmenu@mozilla.com:0.8.3,{847b3a00-7ab1-11d4-8f02-006008948af5}:1.3.5,{e2fda1a4-762b-4020-b5ad-a41df1933103}:1.1.1,{972ce4c6-7e08-4474-a285-3208198ce6fd}:9.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"edsintegration@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird-9.0/extensions/edsintegration@mozilla.com.xpi\",\"mtime\":1325155412000},\"langpack-es-AR@thunderbird.mozilla.org\":{\"descriptor\":\"/usr/lib/thunderbird-9.0/extensions/langpack-es-AR@thunderbird.mozilla.org.xpi\",\"mtime\":1325155602000},\"langpack-es-ES@thunderbird.mozilla.org\":{\"descriptor\":\"/usr/lib/thunderbird-9.0/extensions/langpack-es-ES@thunderbird.mozilla.org.xpi\",\"mtime\":1325155602000},\"messagingmenu@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird-9.0/extensions/messagingmenu@mozilla.com.xpi\",\"mtime\":1325155412000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/thunderbird-9.0/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1329219393000}}},{\"name\":\"app-profile\",\"addons\":{\"{847b3a00-7ab1-11d4-8f02-006008948af5}\":{\"descriptor\":\"/home/usuario/.thunderbird/gucbc2y0.default/extensions/{847b3a00-7ab1-11d4-8f02-006008948af5}\",\"mtime\":1329224625000},\"{e2fda1a4-762b-4020-b5ad-a41df1933103}\":{\"descriptor\":\"/home/usuario/.thunderbird/gucbc2y0.default/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}\",\"mtime\":1329224625000}}}]");
user_pref("extensions.lastAppVersion", "9.0");
user_pref("extensions.lastPlatformVersion", "9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", false);
user_pref("ldap_2.servers.eds.description", "EDS Address Book Bootstrapper");
user_pref("ldap_2.servers.eds.dirType", 3);
user_pref("ldap_2.servers.eds.filename", "eds.mab");
user_pref("ldap_2.servers.eds.position", 1);
user_pref("ldap_2.servers.eds.uri", "moz-abedsdirectory://");
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.rights.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "9.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Trabajo");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Por hacer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Más tarde");
user_pref("mailnews.tags.version", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_optimal_database_size", 7976550);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
