#!/bin/bash

#Borrar resto de repos antiguos de generación

rm -f /etc/apt/sources.list.d/*

chmod 755 -R /etc/apt/sources.list.d/

cat > /etc/apt/sources.list << EOF

#TITLE: Sitio principal de Guadalinex en la Junta de Andalucia
#ID:jda

deb http://v8.guadalinex.org/ubuntu oneiric main restricted universe multiverse
deb http://v8.guadalinex.org/guadalinex-camaleon camaleon main restricted universe multiverse
deb http://v8.guadalinex.org/guadalinex-camaleon camaleon-updates main restricted universe multiverse
deb http://v8.guadalinex.org/guadalinex-camaleon camaleon-security main restricted universe multiverse
deb http://v8.guadalinex.org/guadalinex-camaleon camaleon-backports main restricted universe multiverse
#END
EOF

