# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 169768);
user_pref("browser.migration.version", 5);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage", "file:///usr/share/guadalinex-about/index.html");
user_pref("browser.startup.homepage_override.buildID", "20111228084953");
user_pref("browser.startup.homepage_override.mstone", "rv:9.0.1");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 6);
user_pref("extensions.enabledAddons", "langpack-es-AR@firefox.mozilla.org:9.0.1,langpack-es-CL@firefox.mozilla.org:9.0.1,langpack-es-ES@firefox.mozilla.org:9.0.1,langpack-es-MX@firefox.mozilla.org:9.0.1,{972ce4c6-7e08-4474-a285-3208198ce6fd}:9.0.1");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"langpack-es-AR@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-9.0.1/extensions/langpack-es-AR@firefox.mozilla.org.xpi\",\"mtime\":1325071807000},\"langpack-es-CL@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-9.0.1/extensions/langpack-es-CL@firefox.mozilla.org.xpi\",\"mtime\":1325071807000},\"langpack-es-ES@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-9.0.1/extensions/langpack-es-ES@firefox.mozilla.org.xpi\",\"mtime\":1325071807000},\"langpack-es-MX@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-9.0.1/extensions/langpack-es-MX@firefox.mozilla.org.xpi\",\"mtime\":1325071807000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox-9.0.1/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1326283917000}}}]");
user_pref("extensions.lastAppVersion", "9.0.1");
user_pref("extensions.lastPlatformVersion", "9.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("general.useragent.locale", "es-ES");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 5472);
user_pref("places.history.expiration.transient_optimal_database_size", 8754053);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("startup.homepage_welcome_url", "");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1329044928);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
