#!/bin/bash
#Generated by Álvaro Pinel 2012 <alvaropinel@gmail.com>

DESKTOP_ICONS=`gsettings get org.gnome.desktop.background show-desktop-icons`

echo $DESKTOP_ICONS

if [ $DESKTOP_ICONS = "true" ];then
    if zenity --question --title="Mostrar iconos en el escritorio" --width=350 --text="¿Desea ocultar los iconos del escritorio?"; then
        gsettings set org.gnome.desktop.background show-desktop-icons false
    fi

else
    if zenity --question --title="Mostrar iconos en el escritorio" --width=350 --text="¿Desea mostrar los iconos en el escritorio?"; then
        gsettings set org.gnome.desktop.background show-desktop-icons true
    fi
fi
