#!/bin/sh

set -e
set -x
if test -f Makefile; then
  make distclean
fi
rm -rf *~ *.cache *.m4 config.guess config.log \
	config.status config.sub depcomp ltmain.sh
autoreconf --verbose --install --force
./configure --prefix=/usr \
       --sysconfdir=/etc \
       --datadir=/usr/share \
       --infodir=/usr/share/info \
       --mandir=/usr/share/man
