#!/usr/bin/python
# update-manager-text - easy updating application
#  
#  Copyright (c) 2004-2008 Canonical
#                2004-2008 Michael Vogt
#  
#  Author: Michael Vogt <mvo@debian.org>
# 
#  This program is free software; you can redistribute it and/or 
#  modify it under the terms of the GNU General Public License as 
#  published by the Free Software Foundation; either version 2 of the
#  License, or (at your option) any later version.
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
#  USA

from UpdateManagerText.UpdateManagerText import UpdateManagerText
import sys

from DistUpgrade.DistUpgradeVersion import VERSION
import gettext
from gettext import gettext as _

from optparse import OptionParser

if __name__ == "__main__":
  APP="update-manager"
  DIR="/usr/share/locale"

  gettext.bindtextdomain(APP, DIR)
  gettext.textdomain(APP)

  # Begin parsing of options
  parser = OptionParser()
  parser.add_option ("-V", "--version", action="store_true",
                     dest="show_version", default=False,
                     help=_("Show version and exit"))
  parser.add_option ("--show-description", "--show-description", 
                     action="store_true",
                     dest="show_description", default=False,
                     help=_("Show description of the package instead of "
                            "the changelog"))

  (options, args) = parser.parse_args()

  data_dir="/usr/share/update-manager/"

  if options.show_version:
    print "%s: version %s" % (os.path.basename(sys.argv[0]), VERSION)
    sys.exit(0)

  app = UpdateManagerText(data_dir)
  app.main(options)	
