#!/bin/sh
set -e

. /usr/share/debconf/confmodule

file="$1"

## GUADALINEX

rm -rf $ROOT/etc/apt/sources.list*

cat > $file << EOF
#TITLE: Sitio principal de Guadalinex en la Junta de Andalucia
#ID:jda

deb http://v8.guadalinex.org/ubuntu oneiric main restricted universe multiverse
deb http://v8.guadalinex.org/guadalinex-camaleon camaleon main restricted universe multiverse
deb http://v8.guadalinex.org/guadalinex-camaleon camaleon-updates main restricted universe multiverse
deb http://v8.guadalinex.org/guadalinex-camaleon camaleon-security main restricted universe multiverse
deb http://v8.guadalinex.org/guadalinex-camaleon camaleon-backports main restricted universe multiverse
#END
EOF

## GUADALINEX REPOS END
